apiVersion: v1
kind: Service
metadata:
  name: inference
spec:
  type: {{ .Values.service.type }}
  selector:
    app: inference
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
