replicaCount: 1

image:
  repository: inference
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

volume:
  name: model-volume
  mountPath: /mnt/model
  pvcName: mnist-model-pvc
