apiVersion: v1
kind: Service
metadata:
  name: monitor
spec:
  type: {{ .Values.service.type }}
  selector:
    app: monitor
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
